### ISSUE TITLE
choose time to meet next weekend

### ISSUE THREAD

**Issue by ajschumacher** [friendly-reminder/otters#2]
@jaimeburgos @johnosaurus-rex When is good for you?

**Comment by ajschumacher** [comment]
Sundays at 6?

**Comment by ajschumacher** [comment]
Sunday at 6 decided. @johnosaurus-rex @jaimeburgos

**Comment by johnmwalters** [comment]
Works for me (unless I have a soccer game at 5 PM, then I may be a little
late)
